import { count } from "console";
import { randomChoice, randomInt } from "../../shared/scripts/math";
import { UsernameExistsQuery } from "../database/db-queries/username-exists-query";
import { Database } from "../database/db-query";
import { uniqueNamesGenerator, adjectives, names, animals, colors, countries, languages, NumberDictionary } from 'unique-names-generator';


// Return the first version of the username that doesn't already exist in the database
export async function makeUsernameUnique(username: string) {

    // If the username is already unique, return it
    const usernameExists = await Database.query(UsernameExistsQuery, username);
    if (!usernameExists) {
        return username;
    }

    console.log(`Username ${username} already exists, generating a new one`);

    // If the username already exists, add a number to the end of the username
    let i = 2;
    while (await Database.query(UsernameExistsQuery, `${username}${i}`)) {
        i++;
    }
    return `${username}${i}`;
}

// Generate a completely random username that is guaranteed to be unique in the database
export async function generateRandomUsername(): Promise<string> {
    const separators = ['', '_', '-', ' '];
    const styles = ['lowerCase', 'capital'];
    const specialCharsEnd = ['!', '~'];

    const random = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

    const numberDictionary = NumberDictionary.generate({ min: 10, max: 9999 });

    // Choose a name first for realism
    let username = uniqueNamesGenerator({
        dictionaries: [random([names, names, names, names, names, adjectives, adjectives, adjectives, tetrisWords, tetrisWords, animals, languages]), random([names, names, tetrisWords, tetrisWords])],
        length: random([1, 1, 1, 2]), // 1-word names are now more common
        separator: random(separators),
        style: random(styles) as any
    });

    // Add numbers in a realistic way (e.g., common birth years)
    if (Math.random() < 0.3) {
        username += random([randomInt(1, 9999), randomInt(1, 999), randomInt(1, 99)]);
    }

    if (Math.random() < 0.02) username = username.toUpperCase();

    const char = random(specialCharsEnd);
    if (Math.random() < 0.05) username += char;

    if (Math.random() < 0.05) username = randomInt(1, 100).toString() + username;

    // replace random letter
    if (Math.random() < 0.1) {
        const alphanumeric = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        const randomIndex = Math.floor(Math.random() * username.length);
        const randomChar = alphanumeric[Math.floor(Math.random() * alphanumeric.length)];

        return username.substring(0, randomIndex) + randomChar + username.substring(randomIndex + 1);
    }

    if (username.length > 15) return await generateRandomUsername();

    // Ensure username is unique
    const uniqueUsername = await makeUsernameUnique(username);

    return uniqueUsername;
}

const tetrisWords: string[] = [
    "tetris",
    "tetromino",
    "block",
    "square",
    "line",
    "stack",
    "matrix",
    "well",
    "garbage",
    "spin",
    "twist",
    "finesse",
    "sprint",
    "ultra",
    "marathon",
    "hold",
    "ghost",
    "softdrop",
    "harddrop",
    "topout",
    "backtoback",
    "combos",
    "gravity",
    "guidelines",
    "bag",
    "randomizer",
    "clearing",
    "rotate",
    "infinite",
    "lock",
    "landing",
    "piece",
    "queue",
    "mino",
    "single",
    "double",
    "triple",
    "quadruple",
    "tspin",
    "puzzle",
    "arcade",
    "nintendo",
    "gameboy",
    "dig",
    "mode",
    "platform",
    "scoring",
    "vanish",
    "leftover",
    "sevenbag",
    "color",
    "upcoming",
    "synergy",
    "overlay",
    "partial",
    "cancel",
    "gamer",
    "joystick",
    "controller",
    "keyboard",
    "touchscreen",
    "memory",
    "tetrises",
    "technique",
    "placement",
    "stacking",
    "elimination",
    "turning",
    "calibration",
    "flick",
    "pivot",
    "holdqueue",
    "lockdelay",
    "gravityspeed",
    "lineclear",
    "spinbonus",
    "matrixwidth",
    "superrotation",
    "championship",
    "rotation",
    "cascade",
    "kspin",
    "polyomino",
    "randomseed",
    "mania",
    "challenge",
    "bridging",
    "invisible",
    "tapestry",
    "meltdown",
    "speedrun",
    "mastery",
    "console",
    "forever",
    "battle",
    "reload",
    "perfectclear",
    "b2b",
    "top",
    "splitted",
    "downstack",
    "upstack",
    "midair",
    "countdown",
    "misdrop",
    "precision",
    "tension",
    "rhythmic",
    "slide",
    "corner",
    "infinitespin",
    "danger",
    "vanishzone",
    "zone",
    "restructure",
    "matrixheight",
    "row",
    "column",
    "dimension",
    "engine",
    "formula",
    "shell",
    "multiplier",
    "developer",
    "rotationpoint",
    "boundingbox",
    "unstoppable",
    "grid",
    "overlap",
    "ramp",
    "rank",
    "replays",
    "record",
    "matching",
    "outline",
    "frontier",
    "bounding",
    "horizon",
    "highlight",
    "swirl",
    "vacuum",
    "eclipse",
    "cosmos",
    "zoneattack",
    "ars",
    "bigmode",
    "bonus",
    "flashpoint",
    "spectator",
    "infinitehold",
    "brightness",
    "baseline",
    "srs",
    "extension",
    "tetrio",
    "jstris",
    "blockout",
    "polytope",
    "vantage",
    "quad",
    "nestris",
    "mistris",
    "hypertap",
    "rolling",
    "tapping",
    "maxout",
    "killscreen",
    "transition",
    "digit",
    "leaderboard",
    "multiplayer",
    "zonebattle",
    "pentomino",
    "pajitnov",
    "rogers",
    "stein",
    "skyline",
    "clear",
    "hazard",
    "limit",
    "core",
    "holdlock",
    "jam",
    "tblock",
    "oblock",
    "zblock",
    "sblock",
    "lblock",
    "jblock",
    "iblock",
    "garbagehole",
    "backfire",
    "offset",
    "cleanup",
    "vanishframe",
    "tier",
    "tetris",
  "tetromino",
  "tetrio",
  "block",
  "stack",
  "matrix",
  "well",
  "ghost",
  "spin",
  "twist",
  "hold",
  "sprint",
  "ultra",
  "marathon",
  "vanish",
  "meltdown",
  "limit",
  "misdrop",
  "combos",
  "topple",
  "glitch",
  "gamer",
  "ninja",
  "titan",
  "cosmic",
  "vortex",
  "freeze",
  "spawn",
  "reload",
  "flick",
  "pivot",
  "ravage",
  "havoc",
  "mania",
  "unleashed",
  "warlock",
  "synergy",
  "vanishzone",
  "corner",
  "shift",
  "cluster",
  "hazard",
  "bound",
  "console",
  "arcade",
  "puzzle",
  "majestic",
  "shinobi",
  "arcana",
  "eclipse",
  "infinite",
  "fortress",
  "fortify",
  "speedrun",
  "frametrip",
  "scoreboard",
  "rank",
  "record",
  "rotation",
  "backfire",
  "savant",
  "advance",
  "scramble",
  "xfactor",
  "triforce",
  "vantage",
  "flurry",
  "absorb",
  "genesis",
  "starfall",
  "streamer",
  "caster",
  "ultimate",
  "junction",
  "apex",
  "inbound",
  "outreach",
  "hunter",
  "gatherer",
  "dominion",
  "overwatch",
  "expand",
  "binary",
  "datastream",
  "singularity",
  "unstoppable",
  "breakneck",
  "tidal",
  "pinnacle",
  "peak",
  "endurance",
  "battalion",
  "darkness",
  "phoenix",
  "feather",
  "flash",
  "tackle",
  "slime",
  "pixel",
  "wire",
  "modding",
  "expanse",
  "photon",
  "particles",
  "inventory",
  "bossrush",
  "checkpoint",
  "haven",
  "orchard",
  "frenzy",
  "velocity",
  "cascade",
  "avalanche",
  "radiant",
  "eruption",
  "sapphire",
  "amethyst",
  "stardust",
  "neutron",
  "magnet",
  "raptor",
  "falcon",
  "berserk",
  "trickster",
  "soldier",
  "shards",
  "kindle",
  "hail",
  "ignite",
  "dazzle",
  "shield",
  "reflection",
  "tribute",
  "pulse",
  "voltaic",
  "prism",
  "maestro",
  "tempest",
  "raider",
  "warden",
  "splinter",
  "reckoning",
  "forgemaster",
  "overdrive",
  "amplify",
  "deception",
  "onyx",
  "cobalt",
  "emerald",
  "scarlet",
  "resolute",
  "magnus",
  "basilisk",
  "dread",
  "rune",
  "void",
  "astral",
  "necro",
  "mancer",
  "wraith",
  "frozen",
  "draco",
  "venom",
  "beacon",
  "odyssey",
  "zenith",
  "mirage",
  "chrono",
  "alpha",
  "omega",
  "gamma",
  "delta",
  "exodus",
  "forge",
  "pharos",
  "iris",
  "lotus",
  "mystic",
  "celestial",
  "nexus",
  "rupture",
  "chaos",
  "chance",
  "chase",
  "raven",
  "azure",
  "scarab",
  "silver",
  "orchid",
  "ebony",
  "sable",
  "snow",
  "ember",
  "zeta",
  "sigma",
  "epsilon",
  "iota",
  "kappa",
  "theta"
];
